/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jazzido_PacketDroid_AudioBufferProcessor */

#ifndef _Included_com_jazzido_PacketDroid_AudioBufferProcessor
#define _Included_com_jazzido_PacketDroid_AudioBufferProcessor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jazzido_PacketDroid_AudioBufferProcessor
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jazzido_PacketDroid_AudioBufferProcessor_init
  (JNIEnv *, jobject);

/*
 * Class:     com_jazzido_PacketDroid_AudioBufferProcessor
 * Method:    processBuffer
 * Signature: ([FI)V
 */
JNIEXPORT void JNICALL Java_com_jazzido_PacketDroid_AudioBufferProcessor_processBuffer
  (JNIEnv *, jobject, jfloatArray, jint);

/*
 * Class:     com_jazzido_PacketDroid_AudioBufferProcessor
 * Method:    processBuffer2
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_jazzido_PacketDroid_AudioBufferProcessor_processBuffer2
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
